// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: feed.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countLikes = `-- name: CountLikes :one
SELECT COUNT(*) FROM likes WHERE link_id = $1
`

func (q *Queries) CountLikes(ctx context.Context, linkID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikes, linkID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLike = `-- name: CreateLike :exec
INSERT INTO likes (user_id, link_id) VALUES ($1, $2)
`

type CreateLikeParams struct {
	UserID uuid.UUID
	LinkID uuid.UUID
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) error {
	_, err := q.db.Exec(ctx, createLike, arg.UserID, arg.LinkID)
	return err
}

const createLink = `-- name: CreateLink :exec
INSERT INTO links (user_id, title, url) VALUES ($1, $2, $3)
`

type CreateLinkParams struct {
	UserID uuid.UUID
	Title  string
	Url    string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) error {
	_, err := q.db.Exec(ctx, createLink, arg.UserID, arg.Title, arg.Url)
	return err
}

const deleteVote = `-- name: DeleteVote :exec
DELETE FROM likes WHERE user_id = $1 AND link_id = $2
`

type DeleteVoteParams struct {
	UserID uuid.UUID
	LinkID uuid.UUID
}

func (q *Queries) DeleteVote(ctx context.Context, arg DeleteVoteParams) error {
	_, err := q.db.Exec(ctx, deleteVote, arg.UserID, arg.LinkID)
	return err
}

const linkFeed = `-- name: LinkFeed :many
SELECT 
    l.id AS id,
    l.title,
    l.url,
    l.created_at,
    u.username,
    COUNT(DISTINCT c.id) AS comment_count,
    COUNT(DISTINCT lk.id) AS like_count,
    SUM(CASE WHEN lk.user_id = $1 THEN 1 ELSE 0 END) AS user_voted
FROM 
    links l
JOIN 
    users u ON l.user_id = u.id
LEFT JOIN 
    comments c ON l.id = c.link_id
LEFT JOIN 
    likes lk ON l.id = lk.link_id
GROUP BY 
    l.id, u.username
ORDER BY 
    l.created_at DESC
LIMIT 
    $2
OFFSET 
    $3
`

type LinkFeedParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type LinkFeedRow struct {
	ID           uuid.UUID
	Title        string
	Url          string
	CreatedAt    pgtype.Timestamptz
	Username     string
	CommentCount int64
	LikeCount    int64
	UserVoted    int64
}

func (q *Queries) LinkFeed(ctx context.Context, arg LinkFeedParams) ([]LinkFeedRow, error) {
	rows, err := q.db.Query(ctx, linkFeed, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkFeedRow
	for rows.Next() {
		var i LinkFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.CreatedAt,
			&i.Username,
			&i.CommentCount,
			&i.LikeCount,
			&i.UserVoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userLiked = `-- name: UserLiked :one
SELECT EXISTS(SELECT 1 FROM likes WHERE user_id = $1 AND link_id = $2)
`

type UserLikedParams struct {
	UserID uuid.UUID
	LinkID uuid.UUID
}

func (q *Queries) UserLiked(ctx context.Context, arg UserLikedParams) (bool, error) {
	row := q.db.QueryRow(ctx, userLiked, arg.UserID, arg.LinkID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
