// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Link      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Comment struct {
	ID        uuid.UUID
	ArticleID uuid.UUID
	UserID    uuid.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Like struct {
	ID        uuid.UUID
	ArticleID uuid.UUID
	UserID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Username    string
	Email       string
	Password    string
	ConfirmedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	Context   string
	CreatedAt pgtype.Timestamptz
}
