// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        uuid.UUID
	LinkID    uuid.UUID
	UserID    uuid.UUID
	ParentID  pgtype.UUID
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CommentVote struct {
	ID        uuid.UUID
	CommentID uuid.UUID
	UserID    uuid.UUID
	Vote      int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Link struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Url       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type LinkVote struct {
	ID        uuid.UUID
	LinkID    uuid.UUID
	UserID    uuid.UUID
	Vote      int16
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Avatar      pgtype.Text
	Username    string
	Email       string
	Password    string
	ConfirmedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	Context   string
	CreatedAt pgtype.Timestamptz
}
