// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (avatar, email, username, password) VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateUserParams struct {
	Avatar   pgtype.Text
	Email    string
	Username string
	Password string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Avatar,
		arg.Email,
		arg.Username,
		arg.Password,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO user_tokens (user_id, token, context) VALUES ($1, $2, $3) RETURNING token
`

type CreateUserTokenParams struct {
	UserID  uuid.UUID
	Token   string
	Context string
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, createUserToken, arg.UserID, arg.Token, arg.Context)
	var token string
	err := row.Scan(&token)
	return token, err
}

const deleteUserToken = `-- name: DeleteUserToken :exec
DELETE FROM user_tokens WHERE token = $1 AND context = $2
`

type DeleteUserTokenParams struct {
	Token   string
	Context string
}

func (q *Queries) DeleteUserToken(ctx context.Context, arg DeleteUserTokenParams) error {
	_, err := q.db.Exec(ctx, deleteUserToken, arg.Token, arg.Context)
	return err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userByID = `-- name: UserByID :one
SELECT id, avatar, username, email, confirmed_at, created_at, updated_at FROM users WHERE id = $1
`

type UserByIDRow struct {
	ID          uuid.UUID
	Avatar      pgtype.Text
	Username    string
	Email       string
	ConfirmedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (UserByIDRow, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i UserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Avatar,
		&i.Username,
		&i.Email,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userIDByToken = `-- name: UserIDByToken :one
SELECT user_id FROM user_tokens WHERE token = $1 AND context = $2
`

type UserIDByTokenParams struct {
	Token   string
	Context string
}

func (q *Queries) UserIDByToken(ctx context.Context, arg UserIDByTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, userIDByToken, arg.Token, arg.Context)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const usernameExists = `-- name: UsernameExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE username = $1)
`

func (q *Queries) UsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, usernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
